### ISSUE TITLE
RepairFriendly doesn't seem to work

### ISSUE THREAD

**Issue by JasonHorkles** [2008Choco/VeinMiner#117]
I haven't tested if this applies to items with just 1 durability remaining but even with the option enabled, you can still break your tool by vein mining even when the RepairFriendly option is enabled

**Comment by 2008Choco** [comment]
If I'm understanding your issue correctly, this is intentional and pretty much unavoidable unless tools should take 0 damage when mining blocks with 1 durability remaining... but that would allow the tool to be used infinitely so long as you have vein miner activated. Even when vein mining, the first block has to be broken as though it's a normal block. All other blocks in the vein are destroyed _in addition to_ the first block being destroyed.

The tool is always going to take at least one damage regardless of the `RepairFriendly` option because that option is meant to prevent vein miner from destroying your tool while it's destroying blocks _automatically_ (e.g. you have 10 durability but mine a vein of 16 blocks). The first block, however, is fair game.

_Sorry for the delayed response, I've been extremely busy as of late._

**Comment by JasonHorkles** [comment]
No worries!
What I was saying is that if its durability is a value greater than 1, it will still break the tool

**Comment by 2008Choco** [comment]
Yep! Just tested this locally and it seems you're correct. I'll be sure to fix this.
