### ISSUE TITLE
Template in config unclear

### ISSUE THREAD

**Issue by yuk75** [2008Choco/VeinMiner#16]
```
# An example of how to create templates is as follows (this goes right in the root of the config as its own option. Don't nest it anywhere)
# ToolTemplates:
#   Precedence: CATEGORY_SPECIFIC
#   Global:
#     Type: 'stone' <-- This type can be ANY type at all
#     Name: "&6The VeinMining Stone" <-- Colour codes are supported
#     Lore:
#     - "Colours are supported in &8Lore as well!"
#     - "Here is the second line of lore with &1colour!"
#   Pickaxe:
#     Type: 'diamond_pickaxe' <-- This type MUST be one of the tools defined by the Pickaxe category (i.e. wood, stone, gold, iron, etc. pickaxes)
#     Name: "&cVeinMiner Pickaxe"
```

What is this for and how do I use it completely? I can't find anything to help me. Is this for if I make my own tools OR could I use this to specifically limit the mining of stone, diorite, granite, and andesite to say a stone pickaxe or allow all blocks for a gold pickaxe or hell a stick? If so how do I add the block types?

`InheritMaterialsFromAll: false`

What does this mean? Does this mean the materials fly to me? if I turn it on?

If I want to add clay to the shovel do I add clay or clay ball? The reason I ask is because you have black wool listed and I assume that is for shearing sheep not picking up the wool blocks because you don't use shears for that? But then you have redstone ore instead of redstone so I have no idea.

**Comment by 2008Choco** [comment]
> What is this for and how do I use it completely? I can't find anything to help me. Is this for if I make my own tools OR could I use this to specifically limit the mining of stone, diorite, granite, and andesite to say a stone pickaxe or allow all blocks for a gold pickaxe or hell a stick? If so how do I add the block types?

The tool templates are used if you want a specific item to be used to activate vein miner. For example, if you want vein miner to only work if you use a pickaxe titled "VeinMiner Pickaxe", you would specify that under a tool template :)

> InheritMaterialsFromAll: false
What does this mean? Does this mean the materials fly to me? if I turn it on?

In the block list you will see an "All" category. This is a global blocklist that applies to all tools. If `InheritMaterialsFromAll` is `true`, the "Hand" category will also include materials from the "All" category much like other tools would. If `false`, the materials listed in the "All" category will not be mineable with an empty hand.

> If I want to add clay to the shovel do I add clay or clay ball? The reason I ask is because you have black wool listed and I assume that is for shearing sheep not picking up the wool blocks because you don't use shears for that? But then you have redstone ore instead of redstone so I have no idea.

You want to add the block that should be mineable (the clay block, not the clay balls). The reason wool is listed under the Shears category is in case someone is mining wool blocks in the world with shears. This is the fastest way to mine wool in vanilla Minecraft so it seemed fitting. VeinMiner does not apply to shearing entities.

**Comment by yuk75** [comment]
Ahh thank you so much! So can the tool template be used to allow stone to be vein mined only with say an iron pickaxe? I'm not sure I understand that section fully yet.

**Comment by 2008Choco** [comment]
The templates are per blocklist category. For example, you would have a template for the pickaxe category, a template for the axe category, a template for the shovel category, so on and so forth. They're tools for the specific blocklists, not for the blocks contained in the list. The `type` you see is the type of tool required to break the block in order for VeinMiner to work, not the type that needs to be broken. 

In the default example, the pickaxe template has `type` defined as `diamond_pickaxe` meaning you need a diamond pickaxe to use VeinMiner. The global template has `type` defined as `stone` meaning you need to break a block with a stone item in order to use VeinMiner. The global template may use any type of item to activate VeinMiner, the category templates must use tools of that category (i.e. you can only use pickaxes in the pickaxe category as opposed to a shovel which would make no sense)

**Comment by 2008Choco** [comment]
Closing due to ~2 weeks of no response. Assuming this has been clarified :)
