### ISSUE TITLE
Destroys all the vein when wrong tool used

### ISSUE THREAD

**Issue by yuk75** [2008Choco/VeinMiner#17]
So I had a wooden pickaxe and I mined ironore. A block appeared but then they all vanished and it mined the whole vein....Why did I do this because I haven't played MC in a while and wasn't thinking lol.

So perhaps there should be some sort of way to prevent mining the whole vein if the block will be destroyed. I have no idea if this affects more than just pickaxes.

**Comment by 2008Choco** [comment]
Because wooden pickaxes won't mine iron ore as would a stone pickaxe, it won't drop an item. This is expected vanilla behaviour. VeinMiner should not have a responsibility to halt the mining of a vein if the tool requirements are insufficient. The same applies to the Forge mod on which this plugin is based, so I see no purpose in writing a safeguard for this. Just be careful when you use your vein miner! :)
