### ISSUE TITLE
Unable to revoke permission

### ISSUE THREAD

**Issue by LucoGamer** [2008Choco/VeinMiner#18]
I have checked my permissions plugin (PermissionsEX) and default rank does not have this permission but are still able to use Vein Miner, I ran the command "/pex group default remove veinminer.veinmine.*" just to see if it would work but made no difference so default can still use this without me giving them the permissions to do so.

Furthermore, someone else had this issue 13 days ago and you responded telling him to remove the permission and he responded telling you he was still having issues but you had already closed the request.

**Comment by 2008Choco** [comment]
May I see your permissions.yml (or whatever document is used to represent your permissions?). It could very well be inaccurate. As far as I'm aware, VeinMiner's permissions nodes should not be broken as I've not touched them since very, very early versions of the plugin. I am, however, open to the possibility of them being broken, though I'm skeptical considering there are very few people who bring this to my attention.

**Comment by LucoGamer** [comment]
Thank you for the quick reply, here are my permissions:
https://pastebin.com/dppJFFmT

**Comment by LucoGamer** [comment]
A bit more information, I am running Spigot 1.12.2 #131 with the following plugins, can you look through them and give me any information on conflicting plugins?

Here are my plugins :Autopickup, chatcolor2, chatex, clearlag, coreprotect, crates,eauction,easysetspawn, enjinminecraftplugin, essentials X, griefprevention, guishop,holographic displays, jobs, permissionsex, playervaults, silkspawners, simpleAPI, Simplepets, supervanish, vault, veinminer, virtualpack, votingplugin, mcmmo, votifier, worldedit, worldguard

**Comment by 2008Choco** [comment]
Because `veinminer.veinmine.*` is a default permission (i.e. all groups get this permission by default regardless of whether or not they're specified by a permissions plugin), your default group still has this permission node. You have not negated this permission node in your default group. You must negate default permission nodes if you wish them not to have it.

In your case, for PEx, to add a negative permission node you must prepend a `-` to the permission node. i.e. if you were to add
``` yaml
groups:
  default:
    options:
      default: true
      prefix: '&8[&aMember&8]&7'
    permissions:
    # all your other permission nodes
    - -veinminer.veinmine.*
```
The above will _remove_ the `veinminer.veinmine.*` permission node from the default group and any gruop that inherits from it. Likewise, because you later specified that the `Bedrock` group should have that permission node, it (and any group that inherits from it) will then have that permission node.

**Comment by LucoGamer** [comment]
Have just implemented the changes to my permissions file and this has worked, thank you very much!
