### ISSUE TITLE
Veinminer permissions are useless

### ISSUE THREAD

**Issue by Jordan-Mianite** [2008Choco/VeinMiner#30]
Players without any veinminer permissions are still able to use /veinminer.

**Comment by 2008Choco** [comment]
The command? The code suggests otherwise. `/veinminer reload` is properly restricted by its op-default permission node, as is `pattern`, `toggle`, `blocklist add`, `blocklist remove` and `blocklist list`. The actual vein mining permissions are default, therefore every group will have them unless negated by your permission plugin.

**Comment by Jordan-Mianite** [comment]
Well that makes it so much more work for all the developers. Hence the
subject, permissions are useless.

**Comment by 2008Choco** [comment]
They aren't useless. They very much work as intended. Default permissions are common among plugins and negating them is equally as simple as adding them. Every permission plugin supports the negation of permission nodes (though its syntax may vary, you should refer to your permission plugin's documentation). Because the purpose of VeinMiner is to vein mine, it only makes sense to have these permissions as default. Whether or not you want to restrict this for default users is none of my business... as far as the plugin is concerned, default permissions make sense as the majority of users install this plugin to vein mine.

To say that the permission nodes are useless because you don't want to add a line to your permission plugin configuration or write a simple command is incredibly disrespectful.
