### ISSUE TITLE
VeinMiner's hunger scale settings don't work properly

### ISSUE THREAD

**Issue by Pumamori** [2008Choco/VeinMiner#70]
Good day, if this is the wrong place for this I apologize and feel free to delete / close immediately!
I was wondering if a feature could be added where there's a small (but negligible) downside to vein mining, like tools losing more durability or you consuming more hunger than if you mined manually?

EDIT: TO elaborate, I know there's a hunger setting, it just currently doesn't change anything - we've tried mining 64 blocks all at once and hunger didn't even decrease a little bit!

Thanks in advance!

**Comment by 2008Choco** [comment]
I don't think I intend on adding how much durability will be affected when vein mining. That seems like the job of a third party plugin. VeinMiner doesn't directly modify an item's durability, it lets Minecraft handle it. If a plugin wants to hook into VeinMiner's events and apply additional durability loss, it's welcome to do so, though as far as I'm concerned it's beyond the scope of this plugin.

Though with regards to hunger, if the values aren't doing anything I'd consider that a bug. I'll look into improving this. The algorithm used to affect a player's hunger is from portablejim's VeinMiner for 1.12 or something... so a long while ago. Hunger mechanics have been slightly altered since then so I will see about improving it for version 2.0.0 to make sure that option actually does apply properly.

**Comment by 2008Choco** [comment]
After further investigation, I've determined that the current values in the Hunger configuration are valid and still accurate to current Minecraft mining fatigue (if not a slightly larger debuff).

You should understand a few things to do with hunger:
- Every player has a hidden level of saturation (depending on the food they eat, this might be rather high). Saturation is reduced before actual hunger is. You'll notice this same behaviour in Minecraft. Running after eating a steak will take a while before decreasing your hunger because it gives a lot of saturation.
- If you are an op'd player, you may have the `veinminer.free.hunger` permission which entirely exempts a player from VeinMiner's hunger effects. This permission is not set for any player by default outside of op's

However, the free hunger effect being set to true by default for op'd players is actually technically a bug. No players should have this permission by default. I've resolved this in an upcoming version, see the commit following this comment.
