### ISSUE TITLE
Toggle for specific tools not working.

### ISSUE THREAD

**Issue by Noapoleon** [2008Choco/VeinMiner#77]
![togglebug](https://user-images.githubusercontent.com/61585882/153185962-c19c8505-c8ea-46c7-8194-c05148042b5c.png)
When trying to toggle a tool it will work the first time but afterwards whenever you reuse the command it will always say "VeinMiner successfully toggled on for tool axe" (axe example).
It doesn't toggle it off

**Comment by 2008Choco** [comment]
Toggling specific categories seems to work fine but the issue seems to start happening if you have another category disabled first. In this case here you've toggled off the shovel category, but you then can't toggle off the axe category.

Can still confirm this in the 2.0.0 branch, will have a fix for this in a future update.

**Comment by 2008Choco** [comment]
Kicking myself. Stupid bug lol. Fixed in the next update.

**Comment by Noapoleon** [comment]
nice that was really quick! :)
cool plugin btw
I know it's random but I'm learning to make plugins myself and I was wondering what this field of programming is called?
What I mean is "is there a name for the kind of algorithms veinminer uses that I could google to learn?"
