### ISSUE TITLE
Fix u VeinMiner + Not working

### ISSUE THREAD

**Issue by HarrithReal** [2008Choco/VeinMiner#83]
So if i but /veinminer in my server it won't work it just says /veinminer <Version|reload|blocklist|toollist|toggle|pattern> and when i do /veinminer and then the tap button its just says my name or my friends name this is broken fix it!
or give explan it for me.

**Comment by 2008Choco** [comment]
There is far too little information in this issue for me to act upon. With that being said, there are currently 4.5k servers running VeinMiner without issue. If you are experiencing the issues you are detailing, it's very likely that VeinMiner is erroring on startup on your server because one of the following reasons:
- You are running a server version unsupported by your version of VeinMiner (anything below 1.13 is unsupported)
- You have another plugin interfering with the plugin on startup
