### ISSUE TITLE
How To  Mine multiple blocks of the same type ?In Which Mode?

### ISSUE THREAD

**Issue by RepentStar** [2008Choco/VeinMiner#90]
I upgraded from 1.17.9 to the latest version (2.0.0) and was happy to see three more mining modes, but I found that the default mode also mines blocks in a fixed space, not the same type of blocks within a certain range. May I ask whether the problem is my setting or the plugin?

Minecraft: 1.17.1
java: 17
Plug-in version: 2.0.0
Plugin configuration file: The latest default configuration file
https://github.com/2008Choco/VeinMiner/blob/master/veinminer-bukkit/src/main/resources/config.yml

**Comment by 2008Choco** [comment]
I'm not sure I understand the question. If you're looking to switch mining modes, you can do so with `/veinminer pattern <pattern_id>`. The only current mining patterns are the default one which acts as regular vein miner is expected to work, 3x1 staircases and 3x3 tunnels.

**Comment by RepentStar** [comment]
Sorry for not replying in time. In short, it's how to simply dig for the same blocks near the blocks as in version 1.17.9. For the current version, I find that the default mode is different than before. The current default mode does not select the same nearby block mining. Instead, they mine in a fixed shape, and they don't just mine blocks of the same type.
Please remind me if I'm doing something wrong.

In addition, I am not good at English, and the above words are all from the translator. If you cannot understand it, you can ignore this issue. Thanks.

**Comment by 2008Choco** [comment]
The default mining pattern logic did not change between 1.17.9 and 2.0.0. It should still be mining only the same blocks that you mined initially as you expect. The only case where vein miner will mine different types of blocks is if the two (or more) blocks being mined are aliased under the `aliases` section in the config.yml. Otherwise it should work the same. Perhaps you have another plugin interfering with VeinMiner.
