### ISSUE TITLE
Veinminer triggering FastBreak alert even on supported anticheats.

### ISSUE THREAD

**Issue by NerdTryingToCode** [2008Choco/VeinMiner#92]
When a player use VeinMine, GrimAC along with VulcanAC would flag it as FastBreak.
While Vulcan isn't listed as supported anticheat, shouldn't this be fine with Grim, it seems weird.
This happen to all players.
Server Jar : Purpur 1.19.2
Plugin Version : 2.0.0
Anticheat Version : Both on newest

**Comment by 2008Choco** [comment]
Vulcan is not supported and the reason for that was because of the twists and turns you have to go through to get access to an API jar. To my understanding, their API is not hosted on a public repository and you have to explicitly ask for request to use the API... which just makes no sense to me given that the API is and should be completely separate from the actual implementation of the anti cheat. But this is the way they chose to do things and unless that changes and it is hosted on a public repository, unfortunately I don't feel compelled to support it. They are welcome to make use of VeinMiner API (which is available on a public repository) to integrate support themselves instead.

As for Grim, it's possible that its API has made changes that I'm unaware of. I don't keep up to date on these anti cheats and if the way to allow players to bypass checks has changed, I often miss it. I will need to revisit anti cheat support in the future.

**Comment by 2008Choco** [comment]
I've re-tested GrimAC and I can't seem to get it to flag me at all. I'm going to close this issue due to being unable to replicate it.

As for Vulcan, see the previous comment.
