### ISSUE TITLE
Could you add a mode to deselect blocklist?

### ISSUE THREAD

**Issue by RepentStar** [2008Choco/VeinMiner#95]
I want players can use any tools to destroy any blocks except bedrock , air .....(blocks that should not be destroyed or acquired in Survival Mode). I have tried setting the blocklist to “*”. But it will allow players destroy bedrocks. Or there is a way to achieve this function that I just don't know, if so please help me. Thanks!

**Comment by 2008Choco** [comment]
It seems to be a common request. I don't know how I feel about it. Maybe in the next update.

**Comment by 2008Choco** [comment]
I'm going to close this issue because I don't think I want to add an option to make a block list become a blacklist. In my opinion, I think blacklists will be very confusing, especially if configurable for each category. Block lists are inherently additive and changing them to optionally behave as subtractive doesn't really fit its original purpose.

I do, however, sympathize with the desire to list a lot more blocks with less lines of configuration. As such, I plan on adding support for Minecraft tags in the block list in a future update. Additionally, I wanted to clarify this behaviour:

> I have tried setting the blocklist to “*”. But it will allow players destroy bedrocks

VeinMiner will not enable the breaking of blocks, so if they're unable to break bedrock in vanilla, VeinMiner will not allow them to break it. You should be able to use `*` without worrying about players breaking bedrock.

Thank you for the suggestion anyways.
