### ISSUE TITLE
Update axe blocklist to include cherry logs for 1.20

### ISSUE THREAD

**Issue by ArifulH8** [2008Choco/VeinMiner#96]
The [spigot page](https://www.spigotmc.org/resources/veinminer.12038/) mentions that plugin has been tested in 1.20. However the cherry logs (new block introduced in 1.20) doesn't seem to be able to be veinmined.  

Furthermore, this maybe out of the scope of the plugin, but would it possible for crops that are veinmined have the seed auto planted as a quality of life change.

**Comment by 2008Choco** [comment]
> The [spigot page](https://www.spigotmc.org/resources/veinminer.12038/) mentions that plugin has been tested in 1.20. However the cherry logs (new block introduced in 1.20) doesn't seem to be able to be veinmined.

It has and it will work in 1.20, and yes the default config probably should be updated, but it's not urgent enough to warrant another update. Server owners can absolutely add these blocks manually with `/veinminer blocklist axe add minecraft:cherry_log`. I plan on updating the default block list when Bukkit's experimental changes are merged into the master branch because I expect to drop support for all previous versions. This will be VeinMiner's next update and it seems like the best time to update the block list.

> Furthermore, this maybe out of the scope of the plugin, but would it possible for crops that are veinmined have the seed auto planted as a quality of life change.

Definitely beyond scope of VeinMiner but because of how the plugin breaks blocks, if you get a plugin that does this anyways, it should just work.

**Comment by ArifulH8** [comment]
Hi Thank you for the reply. 
If you don't mind me asking where is the block list located in the code?
I would like to see if I can update "participate" in some java modding.

I tried using [ForestPlant](https://www.spigotmc.org/resources/forestplant-1-16-5-1-20-auto-replanting-crops-saplings.103352/). [A video here](https://imgur.com/a/Wb48vMd) While the initial vien mine does not plant seeds the second vine mine does. I'm not sure why, could be the size of the vein mine? Could you advise?

Also how would one use the API to implement this? Any sort of guide?

Thank you

**Comment by 2008Choco** [comment]
> If you don't mind me asking where is the block list located in the code?
> I would like to see if I can update "participate" in some java modding.

There's some block list-related code dotted around. The [BlockList class](https://github.com/2008Choco/VeinMiner/blob/master/veinminer-server/src/main/java/wtf/choco/veinminer/block/BlockList.java) and [where they're loaded](https://github.com/2008Choco/VeinMiner/blob/master/veinminer-server/src/main/java/wtf/choco/veinminer/VeinMinerServer.java#L373) is probably the most relevant areas for you

> I tried using [ForestPlant](https://www.spigotmc.org/resources/forestplant-1-16-5-1-20-auto-replanting-crops-saplings.103352/). [A video here](https://imgur.com/a/Wb48vMd) While the initial vien mine does not plant seeds the second vine mine does. I'm not sure why, could be the size of the vein mine? Could you advise?

This may just be because the plugin requires you to have seeds in your inventory, which may not have been the case the first time you vein mined. The second time you had seeds in your inventory so it replanted :)

> Also how would one use the API to implement this? Any sort of guide?

You could start with the [PlayerVeinMineEvent](https://choco.wtf/javadocs/veinminer/wtf/choco/veinminer/api/event/player/PlayerVeinMineEvent.html) which will get you all Blocks that were vein mined. You can check if any of them were crops and if so, replant them with a setType() one tick later. Note the "one tick later" though. This event is called before the vein mining actually occurs so you'll want to wait at least a tick before changing the types, otherwise you'll experience some weird behaviour.
